# Application Name
spring.application.name=user-service
 
# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/instabuyDB
spring.datasource.username=root
spring.datasource.password=root@39
 
# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 
# Server Port
server.port=8082